import Head from 'next/head'
import HomeHeader from 'components/homeHeader'

export default function Home() {
  return (
    <>
      <Head>
        <title>Grid Game Creator | NCERT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
          
          {/* Header component */}
          <HomeHeader />

          {/* 8 pairs of input fields in 2 columns */}

          {/* Create Memory Grid */}

          {/* Get a shareable link of created grid */}
          
        </div>
      </main>
    </>
  )
}
